config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://rad-begonia-7ecd23.netlify.app/'
  site_title: Nick Stütz
  site_subtitle_1: Portfolio
  site_subtitle_2: ''
  site_description: >
    Halide is a customizable Jamstack portfolio website theme designed for
    photographers and still image creators. Read the docs at
    [github.com/danurbanowicz/halide](https://github.com/danurbanowicz/halide)
  site_email: none
  site_social_url: none
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  seo:
    site_title: Halide - Jamstack portfolio theme
    site_description: >-
      A customizable, minimalist portfolio website designed for photographers
      and still image creators.
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: true
    quality: 75
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: GitHub
